include: ["assets"]

title: "blog.scot.wtf"
description: "projects, ideas, and more."
url: "https://scotdotwtf.github.io"
domain: blog.scot.wtf

header_pages:
  - index.md
  - about.md
  - contact.md

style: light

footer: 'follow me on <a href="https://twitter.com/catslovejungle">twitter</a>, <a href="https://catslovejungle.bandcamp.com/">bandcamp</a>, or <a href="https://scot.wtf/">more</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

safe: false